/** Map category icon keys (Ionicons-style) to emoji for the landing page. */
export function iconToEmoji(icon: string): string {
  const map: Record<string, string> = {
    flash: "⚡",
    "car-sport": "🚗",
    medkit: "🏥",
    "git-branch": "🔧",
    restaurant: "🍳",
    cut: "✂️",
    leaf: "🌿",
    bug: "🐛",
    eye: "📷",
    heart: "💍",
    construct: "🪵",
    school: "📚",
    home: "🏠",
    thermometer: "❄️",
    "color-palette": "🎨",
    build: "🔩",
    shield: "🛡️",
    camera: "📸",
    shirt: "👔",
    hammer: "🔨",
    flame: "🔥",
    "water-outline": "👕",
    happy: "👶",
    paw: "🐾",
    calendar: "📅",
    body: "🧘",
    cube: "📦",
    easel: "🪴",
    laptop: "💻",
    fitness: "💪",
    barbell: "🏋️",
    "phone-portrait": "📱",
    tv: "📺",
    snow: "❄️",
    "refresh-circle": "🌀",
    brush: "🖌️",
    "code-slash": "💻",
    videocam: "🎥",
    sparkles: "💄",
    pizza: "👨‍🍳",
    nutrition: "🥗",
    "musical-notes": "💃",
    "musical-note": "🎵",
    calculator: "🧮",
    briefcase: "⚖️",
    business: "🏢",
    grid: "🪵",
    umbrella: "🏠",
    "lock-closed": "🔐",
    sunny: "☀️",
    "battery-charging": "⚡",
    contrast: "🪟",
    "fast-food": "🍽️",
    "volume-high": "🎧",
    planet: "🔮",
    language: "🗣️",
    bicycle: "🚴",
    accessibility: "👴",
    "home-outline": "🏗️",
    water: "🏊",
    "shield-checkmark": "🔐",
  };
  return map[icon] ?? "🛠️";
}
