import type { Provider, Category, Conversation, Notification, AdBanner, BookingRequest, EarningEntry } from "./types";

export const CATEGORIES: Category[] = [
  { id: "1",  name: "Driver",              icon: "car-sport",           color: "#4F46E5" },
  { id: "2",  name: "Electrician",         icon: "flash",               color: "#F59E0B" },
  { id: "3",  name: "Plumber",             icon: "git-branch",          color: "#3B82F6" },
  { id: "4",  name: "Carpenter",           icon: "construct",           color: "#92400E" },
  { id: "5",  name: "Cook",                icon: "restaurant",          color: "#EF4444" },
  { id: "6",  name: "Beautician",          icon: "cut",                 color: "#EC4899" },
  { id: "7",  name: "Tutor",               icon: "school",              color: "#8B5CF6" },
  { id: "8",  name: "Cleaner",             icon: "home",                color: "#10B981" },
  { id: "9",  name: "AC Repair",           icon: "thermometer",         color: "#06B6D4" },
  { id: "10", name: "Painter",             icon: "color-palette",       color: "#F97316" },
  { id: "11", name: "Nurse",               icon: "medkit",              color: "#14B8A6" },
  { id: "12", name: "Mechanic",            icon: "build",               color: "#78716C" },
  { id: "13", name: "Guard",               icon: "shield",              color: "#64748B" },
  { id: "14", name: "Photographer",        icon: "camera",              color: "#6366F1" },
  { id: "16", name: "Tailor",              icon: "shirt",               color: "#A855F7" },
  { id: "17", name: "Gardener",            icon: "leaf",                color: "#22C55E" },
  { id: "18", name: "Mason",               icon: "hammer",              color: "#D97706" },
  { id: "19", name: "Welder",              icon: "flame",               color: "#F43F5E" },
  { id: "20", name: "Pest Control",        icon: "bug",                 color: "#84CC16" },
  { id: "21", name: "Laundry",             icon: "water-outline",       color: "#0EA5E9" },
  { id: "22", name: "Baby Sitter",         icon: "happy",               color: "#FBBF24" },
  { id: "23", name: "Pet Care",            icon: "paw",                 color: "#FB923C" },
  { id: "24", name: "Event Planner",       icon: "calendar",            color: "#E879F9" },
  { id: "25", name: "Yoga Trainer",        icon: "body",                color: "#34D399" },
  { id: "26", name: "Packers Movers",      icon: "cube",                color: "#60A5FA" },
  { id: "27", name: "Interior Designer",   icon: "easel",               color: "#C084FC" },
  { id: "28", name: "IT Support",          icon: "laptop",              color: "#38BDF8" },
  { id: "29", name: "Physiotherapist",     icon: "fitness",             color: "#10B981" },
  { id: "30", name: "Gym Trainer",         icon: "barbell",             color: "#EF4444" },
  { id: "31", name: "Mobile Repair",       icon: "phone-portrait",      color: "#6366F1" },
  { id: "32", name: "TV Repair",           icon: "tv",                  color: "#8B5CF6" },
  { id: "33", name: "Fridge Repair",       icon: "snow",                color: "#06B6D4" },
  { id: "34", name: "Washing Mach. Repair",icon: "refresh-circle",      color: "#3B82F6" },
  { id: "35", name: "Graphic Designer",    icon: "brush",               color: "#F59E0B" },
  { id: "36", name: "Web Developer",       icon: "code-slash",          color: "#4F46E5" },
  { id: "37", name: "Videographer",        icon: "videocam",            color: "#EC4899" },
  { id: "38", name: "Makeup Artist",       icon: "sparkles",            color: "#F472B6" },
  { id: "39", name: "Personal Chef",       icon: "pizza",               color: "#EF4444" },
  { id: "40", name: "Dietitian",           icon: "nutrition",           color: "#22C55E" },
  { id: "41", name: "Dance Instructor",    icon: "musical-notes",       color: "#8B5CF6" },
  { id: "42", name: "Music Teacher",       icon: "musical-note",        color: "#6366F1" },
  { id: "43", name: "CA / Accountant",     icon: "calculator",          color: "#0EA5E9" },
  { id: "44", name: "Lawyer",              icon: "briefcase",           color: "#64748B" },
  { id: "45", name: "Property Agent",      icon: "business",            color: "#F97316" },
  { id: "46", name: "Tile & Flooring",     icon: "grid",                color: "#92400E" },
  { id: "47", name: "Roofing",             icon: "umbrella",            color: "#78716C" },
  { id: "48", name: "Locksmith",           icon: "lock-closed",         color: "#F59E0B" },
  { id: "49", name: "CCTV Installation",   icon: "eye",                 color: "#334155" },
  { id: "50", name: "Solar Panel",         icon: "sunny",               color: "#FBBF24" },
  { id: "51", name: "Generator Repair",    icon: "battery-charging",    color: "#10B981" },
  { id: "52", name: "Glass & Glazing",     icon: "contrast",            color: "#38BDF8" },
  { id: "53", name: "Wedding Planner",     icon: "heart",               color: "#EC4899" },
  { id: "54", name: "Caterer",             icon: "fast-food",           color: "#EF4444" },
  { id: "55", name: "DJ & Sound",          icon: "volume-high",         color: "#8B5CF6" },
  { id: "56", name: "Astrologer",          icon: "planet",              color: "#6366F1" },
  { id: "57", name: "Language Tutor",      icon: "language",            color: "#A855F7" },
  { id: "58", name: "Courier",             icon: "bicycle",             color: "#F97316" },
  { id: "59", name: "Elder Care",          icon: "accessibility",       color: "#14B8A6" },
  { id: "60", name: "Home Renovation",     icon: "home-outline",        color: "#F59E0B" },
  { id: "61", name: "Swimming Coach",      icon: "water",               color: "#0EA5E9" },
  { id: "62", name: "Security Audit",      icon: "shield-checkmark",    color: "#4F46E5" },
  { id: "15", name: "More",                icon: "apps",                color: "#94A3B8" },
];

export const AD_BANNERS: AdBanner[] = [
  {
    id: "1",
    title: "Get 20% Off",
    subtitle: "First booking on home cleaning services",
    bgColor: "#FF6B35",
    textColor: "#FFFFFF",
  },
  {
    id: "2",
    title: "Top-Rated Electricians",
    subtitle: "Verified & background-checked pros near you",
    bgColor: "#0F172A",
    textColor: "#FFFFFF",
  },
  {
    id: "3",
    title: "Register as Provider",
    subtitle: "Start earning with your skills today",
    bgColor: "#10B981",
    textColor: "#FFFFFF",
  },
];

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: "p1",
    name: "Rajan Kumar",
    category: "Electrician",
    subcategory: "Residential & Commercial",
    rating: 4.9,
    reviewCount: 312,
    distance: 1.2,
    available: true,
    experience: 8,
    description:
      "Certified electrician with 8+ years of experience in wiring, repairs, and installations. Available for emergency calls anytime.",
    phone: "+919876543210",
    location: "Koramangala, Bangalore",
    serviceRadius: 15,
    serviceCharge: "₹300–₹800",
    workingHours: "Mon–Sat, 8AM–7PM",
    latitude: 12.9352,
    longitude: 77.6245,
    verified: true,
    initials: "RK",
    avatarColor: "#F59E0B",
    services: ["Wiring", "AC Installation", "CCTV", "Solar Panels", "Emergency Repair"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Priya Sharma",
        reviewerInitials: "PS",
        rating: 5,
        comment: "Excellent work! Fixed all electrical issues quickly and professionally.",
        date: "2 days ago",
      },
      {
        id: "r2",
        reviewerName: "Ankit Mehta",
        reviewerInitials: "AM",
        rating: 5,
        comment: "Very punctual and clean work. Highly recommended!",
        date: "1 week ago",
      },
    ],
  },
  {
    id: "p2",
    name: "Suresh Plumber",
    category: "Plumber",
    subcategory: "Pipe Fitting & Repairs",
    rating: 4.7,
    reviewCount: 189,
    distance: 0.8,
    available: true,
    experience: 12,
    description:
      "Expert plumber handling leaks, pipe fitting, bathroom fittings, and water heater installations with quality guaranteed.",
    phone: "+919988776655",
    location: "HSR Layout, Bangalore",
    serviceRadius: 10,
    serviceCharge: "₹250–₹600",
    workingHours: "Mon–Sun, 7AM–8PM",
    latitude: 12.9121,
    longitude: 77.6446,
    verified: true,
    initials: "SP",
    avatarColor: "#3B82F6",
    services: ["Pipe Repair", "Bathroom Fitting", "Water Heater", "Leak Detection", "Drain Cleaning"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Kavita Nair",
        reviewerInitials: "KN",
        rating: 5,
        comment: "Fixed the leak in under an hour. Very professional.",
        date: "3 days ago",
      },
      {
        id: "r2",
        reviewerName: "Mohan Das",
        reviewerInitials: "MD",
        rating: 4,
        comment: "Good work, fair pricing. Will call again.",
        date: "2 weeks ago",
      },
    ],
  },
  {
    id: "p3",
    name: "Lakshmi Devi",
    category: "Cook",
    subcategory: "South Indian & Multi-Cuisine",
    rating: 4.8,
    reviewCount: 97,
    distance: 2.1,
    available: true,
    experience: 6,
    description:
      "Home cook specializing in South Indian, North Indian, and Chinese cuisine. Perfect for events, daily cooking, and tiffin services.",
    phone: "+919123456789",
    location: "Indiranagar, Bangalore",
    serviceRadius: 8,
    serviceCharge: "₹500–₹1500",
    workingHours: "Mon–Sat, 7AM–2PM",
    latitude: 12.9784,
    longitude: 77.6408,
    verified: true,
    initials: "LD",
    avatarColor: "#EF4444",
    services: ["Daily Cooking", "Event Catering", "Tiffin Service", "Baking", "Party Orders"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Ramesh Iyer",
        reviewerInitials: "RI",
        rating: 5,
        comment: "Amazing food! Exactly like home-cooked meals. Very hygienic.",
        date: "5 days ago",
      },
      {
        id: "r2",
        reviewerName: "Deepa Rao",
        reviewerInitials: "DR",
        rating: 5,
        comment: "Hired for our office party. Everyone loved the food!",
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: "p4",
    name: "Vijay Sharma",
    category: "Carpenter",
    subcategory: "Furniture & Interior",
    rating: 4.6,
    reviewCount: 143,
    distance: 3.4,
    available: false,
    experience: 15,
    description:
      "Master carpenter with 15 years in custom furniture, wardrobes, kitchen cabinets, and all woodwork. Quality assured.",
    phone: "+919765432100",
    location: "Jayanagar, Bangalore",
    serviceRadius: 20,
    serviceCharge: "₹600–₹2000",
    workingHours: "Mon–Sat, 9AM–6PM",
    latitude: 12.9250,
    longitude: 77.5833,
    verified: true,
    initials: "VS",
    avatarColor: "#92400E",
    services: ["Custom Furniture", "Kitchen Cabinets", "Wardrobes", "Repairs", "Wooden Flooring"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Sunita Patel",
        reviewerInitials: "SP",
        rating: 5,
        comment: "Beautiful custom wardrobe! Excellent craftsmanship.",
        date: "1 week ago",
      },
      {
        id: "r2",
        reviewerName: "Girish Kulkarni",
        reviewerInitials: "GK",
        rating: 4,
        comment: "Good work on our kitchen cabinets. Slightly delayed but worth it.",
        date: "1 month ago",
      },
    ],
  },
  {
    id: "p5",
    name: "Meera Beautician",
    category: "Beautician",
    subcategory: "Bridal & Makeup",
    rating: 4.9,
    reviewCount: 256,
    distance: 1.5,
    available: true,
    experience: 9,
    description:
      "Professional beautician offering bridal makeup, hair styling, facials, and beauty treatments at your doorstep.",
    phone: "+919456789012",
    location: "BTM Layout, Bangalore",
    serviceRadius: 12,
    serviceCharge: "₹800–₹5000",
    workingHours: "Tue–Sun, 10AM–8PM",
    latitude: 12.9166,
    longitude: 77.6101,
    verified: true,
    initials: "MB",
    avatarColor: "#EC4899",
    services: ["Bridal Makeup", "Hair Styling", "Facial", "Threading", "Nail Art"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Ankita Joshi",
        reviewerInitials: "AJ",
        rating: 5,
        comment: "Made me look stunning for my wedding! Highly recommend!",
        date: "4 days ago",
      },
      {
        id: "r2",
        reviewerName: "Pooja Reddy",
        reviewerInitials: "PR",
        rating: 5,
        comment: "Perfect for home service. Very professional setup.",
        date: "2 weeks ago",
      },
    ],
  },
  {
    id: "p6",
    name: "Arjun Tutor",
    category: "Tutor",
    subcategory: "Math & Science",
    rating: 4.8,
    reviewCount: 78,
    distance: 0.6,
    available: true,
    experience: 5,
    description:
      "IIT graduate offering home tuition for Maths, Physics, and Chemistry. Classes 8-12 and competitive exam coaching.",
    phone: "+919345678901",
    location: "JP Nagar, Bangalore",
    serviceRadius: 10,
    serviceCharge: "₹500–₹1000/hr",
    workingHours: "Mon–Fri, 4PM–9PM",
    latitude: 12.9063,
    longitude: 77.5857,
    verified: true,
    initials: "AT",
    avatarColor: "#8B5CF6",
    services: ["Math", "Physics", "Chemistry", "JEE Prep", "NEET Prep"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Rahul Verma",
        reviewerInitials: "RV",
        rating: 5,
        comment: "My son's marks improved from 60 to 92 in 3 months!",
        date: "1 week ago",
      },
      {
        id: "r2",
        reviewerName: "Smita Naik",
        reviewerInitials: "SN",
        rating: 5,
        comment: "Excellent teaching method. Very patient and thorough.",
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: "p7",
    name: "Deepak AC Repair",
    category: "AC Repair",
    subcategory: "All Brands Servicing",
    rating: 4.7,
    reviewCount: 204,
    distance: 2.8,
    available: true,
    experience: 11,
    description:
      "Certified AC technician for all brands — servicing, repair, gas refilling, and installation. 90-day service warranty.",
    phone: "+919234567890",
    location: "Electronic City, Bangalore",
    serviceRadius: 25,
    serviceCharge: "₹400–₹2500",
    workingHours: "Mon–Sun, 9AM–9PM",
    latitude: 12.8399,
    longitude: 77.6770,
    verified: true,
    initials: "DA",
    avatarColor: "#06B6D4",
    services: ["AC Service", "Gas Refilling", "Installation", "PCB Repair", "Remote Repair"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Anil Kumar",
        reviewerInitials: "AK",
        rating: 5,
        comment: "Fixed my AC in 45 minutes. Excellent and quick service!",
        date: "Yesterday",
      },
      {
        id: "r2",
        reviewerName: "Beena Thomas",
        reviewerInitials: "BT",
        rating: 4,
        comment: "Professional service. Explained the issue clearly.",
        date: "5 days ago",
      },
    ],
  },
  {
    id: "p8",
    name: "Fatima House Clean",
    category: "Cleaner",
    subcategory: "Deep Cleaning",
    rating: 4.8,
    reviewCount: 167,
    distance: 1.9,
    available: true,
    experience: 7,
    description:
      "Professional home cleaning service including deep cleaning, kitchen, bathroom, and post-move-out cleaning.",
    phone: "+919876012345",
    location: "Whitefield, Bangalore",
    serviceRadius: 15,
    serviceCharge: "₹800–₹3000",
    workingHours: "Mon–Sat, 8AM–6PM",
    latitude: 12.9698,
    longitude: 77.7500,
    verified: false,
    initials: "FC",
    avatarColor: "#10B981",
    services: ["Deep Cleaning", "Kitchen Cleaning", "Bathroom", "Post-Move", "Sofa Cleaning"],
    reviews: [
      {
        id: "r1",
        reviewerName: "Divya Krishnan",
        reviewerInitials: "DK",
        rating: 5,
        comment: "My apartment has never been this clean! Great team!",
        date: "2 days ago",
      },
      {
        id: "r2",
        reviewerName: "Harish Nair",
        reviewerInitials: "HN",
        rating: 5,
        comment: "On time, professional, and thorough. Will book again.",
        date: "2 weeks ago",
      },
    ],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    providerId: "p1",
    providerName: "Rajan Kumar",
    providerCategory: "Electrician",
    providerAvatarColor: "#F59E0B",
    providerInitials: "RK",
    lastMessage: "I will be there at 10 AM tomorrow.",
    lastMessageTime: "10:32 AM",
    unreadCount: 2,
    phone: "+919876543210",
  },
  {
    id: "c2",
    providerId: "p3",
    providerName: "Lakshmi Devi",
    providerCategory: "Cook",
    providerAvatarColor: "#EF4444",
    providerInitials: "LD",
    lastMessage: "Sure, I can prepare South Indian meals daily.",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    phone: "+919123456789",
  },
  {
    id: "c3",
    providerId: "p5",
    providerName: "Meera Beautician",
    providerCategory: "Beautician",
    providerAvatarColor: "#EC4899",
    providerInitials: "MB",
    lastMessage: "Booking confirmed for Saturday at 2 PM.",
    lastMessageTime: "Mon",
    unreadCount: 0,
    phone: "+919456789012",
  },
];

export const MOCK_BOOKING_REQUESTS: BookingRequest[] = [
  {
    id: "br1",
    conversationId: "c1",
    customerId: "cu1",
    customerName: "Arjun Patel",
    customerInitials: "AP",
    customerAvatarColor: "#3B82F6",
    service: "Electrical Wiring Check",
    date: "Sat, 10 May",
    time: "10:00 AM",
    amount: "₹500",
    status: "pending",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "br2",
    conversationId: "c2",
    customerId: "cu2",
    customerName: "Sneha Reddy",
    customerInitials: "SR",
    customerAvatarColor: "#EC4899",
    service: "AC Installation",
    date: "Sun, 11 May",
    time: "2:00 PM",
    amount: "₹1,200",
    status: "pending",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "br3",
    conversationId: "c3",
    customerId: "cu3",
    customerName: "Rahul Nair",
    customerInitials: "RN",
    customerAvatarColor: "#10B981",
    service: "CCTV Setup",
    date: "Mon, 12 May",
    time: "11:00 AM",
    amount: "₹800",
    status: "accepted",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "br4",
    conversationId: "c4",
    customerId: "cu4",
    customerName: "Divya Menon",
    customerInitials: "DM",
    customerAvatarColor: "#F59E0B",
    service: "Emergency Repair",
    date: "Fri, 9 May",
    time: "9:00 AM",
    amount: "₹350",
    status: "customer_confirmed_completed",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

// ── Earnings mock data ─────────────────────────────────────────────────────

function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const MOCK_EARNINGS: EarningEntry[] = [
  { id: "e1",  customerName: "Divya Menon",   customerInitials: "DM", customerAvatarColor: "#F59E0B", service: "Emergency Repair",     date: "Fri, 9 May",   completedAt: daysAgo(2),  amount: 350  },
  { id: "e2",  customerName: "Arjun Patel",   customerInitials: "AP", customerAvatarColor: "#3B82F6", service: "Electrical Wiring",   date: "Thu, 8 May",   completedAt: daysAgo(3),  amount: 600  },
  { id: "e3",  customerName: "Priya Sharma",  customerInitials: "PS", customerAvatarColor: "#10B981", service: "Fan Installation",    date: "Wed, 7 May",   completedAt: daysAgo(4),  amount: 450  },
  { id: "e4",  customerName: "Rahul Nair",    customerInitials: "RN", customerAvatarColor: "#8B5CF6", service: "CCTV Setup",          date: "Tue, 6 May",   completedAt: daysAgo(5),  amount: 800  },
  { id: "e5",  customerName: "Sneha Reddy",   customerInitials: "SR", customerAvatarColor: "#EC4899", service: "Switchboard Fix",     date: "Mon, 5 May",   completedAt: daysAgo(6),  amount: 300  },
  { id: "e6",  customerName: "Kiran Kumar",   customerInitials: "KK", customerAvatarColor: "#06B6D4", service: "AC Power Wiring",     date: "Sun, 4 May",   completedAt: daysAgo(7),  amount: 1100 },
  { id: "e7",  customerName: "Meera Joshi",   customerInitials: "MJ", customerAvatarColor: "#F97316", service: "Inverter Install",    date: "Sat, 3 May",   completedAt: daysAgo(8),  amount: 950  },
  { id: "e8",  customerName: "Anil Das",      customerInitials: "AD", customerAvatarColor: "#EF4444", service: "Light Fitting",       date: "Fri, 2 May",   completedAt: daysAgo(9),  amount: 250  },
  { id: "e9",  customerName: "Geeta Rao",     customerInitials: "GR", customerAvatarColor: "#14B8A6", service: "DB Board Repair",     date: "Thu, 1 May",   completedAt: daysAgo(10), amount: 700  },
  { id: "e10", customerName: "Suresh Pillai", customerInitials: "SP", customerAvatarColor: "#64748B", service: "Earthing Check",      date: "Wed, 30 Apr",  completedAt: daysAgo(11), amount: 500  },
  { id: "e11", customerName: "Ritu Singh",    customerInitials: "RS", customerAvatarColor: "#4F46E5", service: "Water Heater Fix",    date: "Tue, 29 Apr",  completedAt: daysAgo(12), amount: 420  },
  { id: "e12", customerName: "Vijay Menon",   customerInitials: "VM", customerAvatarColor: "#F59E0B", service: "Security Wiring",     date: "Mon, 28 Apr",  completedAt: daysAgo(13), amount: 1350 },
  { id: "e13", customerName: "Lakshmi Iyer",  customerInitials: "LI", customerAvatarColor: "#EC4899", service: "TV Point Setup",      date: "Sun, 27 Apr",  completedAt: daysAgo(14), amount: 280  },
  { id: "e14", customerName: "Deepak Verma",  customerInitials: "DV", customerAvatarColor: "#10B981", service: "Generator Repair",    date: "Sat, 26 Apr",  completedAt: daysAgo(15), amount: 900  },
  { id: "e15", customerName: "Neha Gupta",    customerInitials: "NG", customerAvatarColor: "#8B5CF6", service: "Solar Panel Wiring",  date: "Fri, 25 Apr",  completedAt: daysAgo(16), amount: 1800 },
  { id: "e16", customerName: "Ramesh Shetty", customerInitials: "RS", customerAvatarColor: "#3B82F6", service: "Power Backup Setup",  date: "Thu, 24 Apr",  completedAt: daysAgo(17), amount: 650  },
  { id: "e17", customerName: "Anita Bhat",    customerInitials: "AB", customerAvatarColor: "#06B6D4", service: "Cable Management",    date: "Wed, 23 Apr",  completedAt: daysAgo(18), amount: 380  },
  { id: "e18", customerName: "Sanjay Roy",    customerInitials: "SR", customerAvatarColor: "#F97316", service: "Concealed Wiring",    date: "Tue, 22 Apr",  completedAt: daysAgo(19), amount: 2200 },
  { id: "e19", customerName: "Pooja Tiwari",  customerInitials: "PT", customerAvatarColor: "#EF4444", service: "Plug Point Fix",      date: "Mon, 21 Apr",  completedAt: daysAgo(20), amount: 180  },
  { id: "e20", customerName: "Kartik Menon",  customerInitials: "KM", customerAvatarColor: "#14B8A6", service: "AC Installation",     date: "Sun, 20 Apr",  completedAt: daysAgo(21), amount: 1500 },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "New Message",
    body: "Rajan Kumar: I will be there at 10 AM tomorrow.",
    time: "10 min ago",
    read: false,
    type: "message",
  },
  {
    id: "n2",
    title: "Booking Confirmed",
    body: "Your appointment with Meera Beautician is confirmed for Saturday.",
    time: "2 hrs ago",
    read: false,
    type: "booking",
  },
  {
    id: "n3",
    title: "Review Received",
    body: "Priya Sharma left you a 5-star review!",
    time: "Yesterday",
    read: true,
    type: "review",
  },
  {
    id: "n4",
    title: "Nearby Provider Added",
    body: "A new AC Repair specialist joined SkillAd near you.",
    time: "2 days ago",
    read: true,
    type: "system",
  },
];
